author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/KeyboardAdjuster"
github_file_prefix: "https://github.com/lionheart/KeyboardAdjuster/tree/2.0.0"
xcodebuild_arguments: ["-project", "KeyboardAdjuster.xcodeproj", "-scheme", "KeyboardAdjuster"]
readme: "README.md"
copyright: "&copy; 2016-2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"
use_safe_filenames: true

